stages:
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  image: openjdk:8-jdk-slim
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
  script:
    - ./gradlew clean check
