image: java:8-jdk

stages:
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  script:
    - ./gradlew clean check
